[package]
name = "example1"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
tokio = {version = "1.40.0", features = ["full"]}
tokio-postgres =  { version = "0.7.11", features = ["with-chrono-0_4"] }
